version: '2'
services:
  pytalk:
     build:
        context: .
        dockerfile: Dockerfile
     expose:
        - "9999"
     volumes:
        - ./books:/jupyter
     command: jupyter-notebook --config=config.py

