name: 'Core Setup'
description: 'Sets up Python and uv with dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: true

runs:
    using: "composite"
    steps:
      - uses: actions/checkout@v4

      # Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a

      - name: Set up Python and install dependencies
        shell: bash
        run: |
          uv python install ${{ inputs.python-version }}
          uv venv
          uv pip install --no-cache-dir  -r requirements.txt