name: deploy-book

on:
  - workflow_dispatch
  - push

permissions:
  contents: read

# These jobs install dependencies, build the book, and pushes it to `gh-pages`
jobs:
  book:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        # Install uv
        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            python-version: '3.12'


        - name: Set up Python and install dependencies
          shell: bash
          run: |
            uv venv
            uv pip install --no-cache-dir  -r requirements.txt

        - name: Install jupyterbook
          shell: bash
          run: |
            uv pip install --no-cache-dir jupyter-book

        # Build the book
        - name: Build the book
          shell: bash
          run: |
            ls -all
            uv run jupyter-book clean book
            uv run jupyter-book build book

        # Upload the book
        - name: Archive book
          uses: actions/upload-artifact@v4
          with:
            name: book
            path: book/_build/html/
            retention-days: 1



  marimo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      # Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'


      - name: Set up Python and install dependencies
        shell: bash
        run: |
          uv venv
          uv pip install --no-cache-dir  -r requirements.txt


      # Convert all notebooks
      - name: Convert notebooks to HTML
        run: |
          mkdir -p artifacts/marimo
          for file in notebooks/*.py; do
            if [ -f "$file" ]; then
              filename=$(basename "$file" .py)
              echo "Converting $filename.py to HTML..."
              # Can't work as it relies on license files not part of this repo
              uv run marimo export html "$file" -o "artifacts/marimo/${filename}.html"
            fi
          done

      - name: Upload HTML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: marimo
          path: artifacts/marimo
          retention-days: 1

  deploy-book:
    runs-on: ubuntu-latest
    needs: [ book, marimo ]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v2.1.1
