# This workflow builds and deploys marimo notebooks to GitHub Pages
# It runs automatically when changes are pushed to the main branch or can be triggered manually

name: Deploy to GitHub Pages

# Defines when the workflow will run
on:
  push:
    branches: ['main']  # Trigger on pushes to main branch
  workflow_dispatch:    # Allow manual triggering from the GitHub UI

permissions:
  contents: 'write'

jobs:
  # The build job exports marimo notebooks to static HTML/WebAssembly
  marimo:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - uses: tschm/marimushka/actions/export@v0.0.16
        with:
          notebooks: notebooks
          publish: 'true'
