name: deploy-book

on: [push]

permissions:
  contents: read

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  book:
    runs-on: ubuntu-latest
    steps:
        - name: Install uv
          uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a

        - name: Create virtual environment
          run: |
            - uv venv


        - name: Install jupyterbook
          shell: bash
          run: |
            uv pip install --no-cache-dir jupyter-book sphinx-math-dollar


        # Build the book
        - name: Build the book
          shell: bash
          run: |
            uv run jupyter-book clean book
            uv run jupyter-book build book

        # Upload the book
        - name: Archive book
          uses: actions/upload-artifact@v4
          with:
            name: book
            path: book/_build/html/
            retention-days: 1



  marimo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a

      - name: Create virtual environment
        run: |
          uv venv

      - name: Install dependencies with uv
        run: |
          uv pip install --no-cache-dir  -r requirements.txt

      - name: Install marimo
        run: |
          uv pip install --no-cache-dir  marimo

      - name: Convert notebooks to HTML
        run: |
          mkdir -p artifacts/marimo
          for file in notebooks/*.py; do
            if [ -f "$file" ]; then
              filename=$(basename "$file" .py)
              echo "Converting $filename.py to HTML..."
              # Can't work as it relies on license files not part of this repo
              uv run marimo export html "$file" -o "artifacts/marimo/${filename}.html"
            fi
          done

      - name: Upload HTML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: marimo
          path: artifacts/marimo
          retention-days: 1

  deploy-book:
    runs-on: ubuntu-latest
    needs: [ book, marimo ]


    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: .book

    - name: Create .nojekyll
      shell: bash
      run: touch .book/.nojekyll

    - name: GitHub Pages action
      uses: JamesIves/github-pages-deploy-action@v4.7.2
      with:
          branch: gh-pages
          folder: book/_build/html
