name: "book"
# Documentation and book generation workflow
# This workflow builds and publishes the project documentation, including API docs,
# test coverage reports, and interactive notebooks.

on:
  push:
    branches:
      - main

jobs:
  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: jebel-quant/marimushka@v0.1.3
        with:
          notebooks: 'book/marimo'

  book:
    # Combine all documentation and publish to GitHub Pages
    runs-on: "ubuntu-latest"
    needs: [marimo]  # Wait for all other jobs to complete

    permissions:
      contents: read
      pages: write            # Permission to deploy to Pages
      id-token: write         # Permission to verify deployment origin

    steps:
      - uses: tschm/cradle/actions/book@v0.1.76
        with:
          title: "Baby Names"
          links: |
            {
              "Notebooks": "./marimushka/index.html"
            }
