# This workflow builds and deploys marimo notebooks to GitHub Pages
# It runs automatically when changes are pushed to the main branch or can be triggered manually

name: Deploy to GitHub Pages

# Defines when the workflow will run
on:
  push:
    branches: ['main']  # Trigger on pushes to main branch
  workflow_dispatch:    # Allow manual triggering from the GitHub UI

# Concurrency settings to manage multiple workflow runs
concurrency:
  group: 'pages'             # Only one workflow in the 'pages' group can run at a time
  cancel-in-progress: false  # Don't cancel in-progress runs when a new one is triggered

# Environment variables used by the workflow
env:
  UV_SYSTEM_PYTHON: 1   # Use system Python with uv package manager

jobs:
  # The build job exports marimo notebooks to static HTML/WebAssembly
  marimo:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - uses: tschm/marimushka/actions/export@v0.0.13
        with:
          notebooks: notebooks


  # Job to combine all artifacts and prepare them for deployment
  # This job runs after both jupyter and marimo jobs have completed
  deploy:
    runs-on: ubuntu-latest

    needs: [marimo]  # This job depends on both jupyter and marimo jobs

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Publish book
        id: deployment
        uses: tschm/cradle/actions/book@v0.1.71
