# Workflow for building and deploying the Jupyter Book documentation
# This workflow builds both Jupyter and Marimo environments, then publishes the book to GitHub Pages

name: deploy-book

# Trigger the workflow on push events
on:
  - push

# Default permissions for all jobs
permissions:
  contents: read

# These jobs install dependencies, build the book, and pushes it to `gh-pages`
jobs:
  # Job to set up and build the Jupyter environment
  jupyter:
    runs-on: ubuntu-latest
    steps:
        # Set up the virtual environment with all dependencies
        - name: "Build the virtual environment for ${{ github.repository }}"
          uses: tschm/cradle/actions/environment@v0.1.63

        # Run Jupyter-specific setup and processing
        - uses: tschm/cradle/actions/jupyter@v0.1.64

  # Job to set up and build the Marimo interactive notebook environment
  marimo:
    runs-on: ubuntu-latest
    steps:
      # Set up the virtual environment with all dependencies
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.63

      # Run Marimo-specific setup and processing
      - uses: tschm/cradle/actions/marimo@v0.1.63
        with:
          source_folder: 'notebooks'  # Specify the folder containing Marimo notebooks

  # Job to deploy the built book to GitHub Pages
  deploy-book:
    runs-on: ubuntu-latest
    # This job depends on both jupyter and marimo jobs completing successfully
    needs: [ jupyter, marimo ]

    # Need write permission to push to gh-pages branch
    permissions:
      contents: write

    steps:
      # Check out the repository code
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      # Build and deploy the book to GitHub Pages
      - uses: tschm/cradle/actions/book@v0.1.66
