# Workflow for building and deploying the Jupyter Book documentation
# This workflow builds both Jupyter and Marimo environments, then publishes the book to GitHub Pages

name: deploy-book

# Trigger the workflow on push events
on:
  - push

# Default permissions for all jobs
permissions:
  contents: read

# These jobs install dependencies, build the book, and pushes it to `gh-pages`
jobs:
  # Job to set up and build the Jupyter environment
  jupyter:
    runs-on: ubuntu-latest
    steps:
        # Set up the virtual environment with all dependencies
        - name: "Build the virtual environment for ${{ github.repository }}"
          uses: tschm/cradle/actions/environment@v0.1.69

        - uses: tschm/cradle/actions/jupyter@v0.1.69


  # Job to set up and build the Marimo interactive notebook environment
  marimo:
    runs-on: ubuntu-latest
    steps:
      # Set up the virtual environment with all dependencies
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.69

      - name: Convert notebook to HTML
        run: |
          uv run pip install --no-cache-dir marimo
          mkdir -p artifacts/marimo
          #uv run marimo export html app.py -o artifacts/marimo/index.html
          uv run marimo export html-wasm notebooks/boring.py -o artifacts/marimo --mode edit

      - run: |
          ls -all 
          ls -all artifacts
          
      - name: Upload HTML artifacts
        #if: ${{ env.ACT != 'true' }}  # Skip if running with 'act'
        uses: actions/upload-artifact@v4
        with:
          name: marimo
          path: artifacts/marimo
          retention-days: 1

      #- uses: tschm/cradle/actions/marimo@v0.1.69
      #  with:
      #    source_folder: 'notebooks'  # Specify the folder containing Marimo notebooks

  build:
    runs-on: ubuntu-latest
    needs: [jupyter, marimo]

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - run: |
          ls -all
          ls -all artifacts
          
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: artifacts/

  # Job to deploy the built book to GitHub Pages
  deploy-book:
    runs-on: ubuntu-latest
    # This job depends on both jupyter and marimo jobs completing successfully
    needs: build
    # Need write permission to push to gh-pages branch
    permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
