name: deploy-book

on:
  - workflow_dispatch
  - push

permissions:
  contents: read

# These jobs install dependencies, build the book, and pushes it to `gh-pages`
jobs:
  book:
    runs-on: ubuntu-latest
    steps:
        - name: "Build the virtual environment for ${{ github.repository }}"
          uses: cvxgrp/.github/actions/environment/pip@main

        - uses: cvxgrp/.github/actions/jupyter@v2.1.1

  marimo:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment/pip@main

      - uses: cvxgrp/.github/actions/marimo@v2.1.1

  deploy-book:
    runs-on: ubuntu-latest
    needs: [ book, marimo ]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v2.1.1
