name: deploy-book

on:
  - workflow_dispatch
  - push

permissions:
  contents: read

# These jobs install dependencies, build the book, and pushes it to `gh-pages`
jobs:
  marimo:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/uv/marimo@v2.0.17

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/uv/jupyter@v2.0.17

  deploy-book:
    runs-on: ubuntu-latest
    needs: [ jupyter, marimo ]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v2.0.17
