name: deploy-book

on:
  - push

permissions:
  contents: read

# These jobs install dependencies, build the book, and pushes it to `gh-pages`
jobs:
  jupyter:
    runs-on: ubuntu-latest
    steps:
        - name: "Build the virtual environment for ${{ github.repository }}"
          uses: tschm/cradle/actions/environment@v0.1.68

        - uses: tschm/cradle/actions/jupyter@v0.1.68

  marimo:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.68

      - uses: tschm/cradle/actions/marimo@v0.1.68
        with:
          source_folder: 'notebooks'

  deploy-book:
    runs-on: ubuntu-latest
    needs: [ jupyter, marimo ]

    permissions:
      contents: write

    steps:
      # Check out the repository code
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: tschm/cradle/actions/book@v0.1.68
