name: deploy-book

on:
  - push

permissions:
  contents: read

# These jobs install dependencies, build the book, and pushes it to `gh-pages`
jobs:
  jupyter:
    runs-on: ubuntu-latest
    steps:
        - name: "Build the virtual environment for ${{ github.repository }}"
          uses: cvxgrp/.github/actions/environment@v2.2.8

        - uses: cvxgrp/.github/actions/jupyter@v2.2.8

  marimo:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/marimo@v2.2.8
        with:
          source_folder: 'notebooks'

  deploy-book:
    runs-on: ubuntu-latest
    needs: [ jupyter, marimo ]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v2.2.8
