name: Core Workflow
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      # Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a

      - name: Set up Python and install dependencies
        shell: bash
        run: |
          uv python install ${{ inputs.python-version }}
          uv venv
          uv pip install --no-cache-dir  -r requirements.txt