name: "Marimo Notebooks"
# Workflow for running marimo notebooks
# This workflow runs all marimo notebooks in the book/marimo directory in parallel
# to ensure they execute without errors.

on:
  push:  # Triggered on every push to the repository

permissions:
  contents: read  # Read-only access to repository contents


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: tschm/marimushka/.github/workflows/test@main
        with:
          notebook-dir: 'notebooks'
