name: Bump version

on:
  workflow_dispatch

jobs:
  tagging:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}  # This will output the tag for other jobs
    steps:
      - name: Generate Tag
        id: tag_version
        uses: tschm/cradle/actions/tag@v0.1.66
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Output Tag
        run: |
            echo "Tag: ${{ steps.tag_version.outputs.new_tag }}"
