# Workflow for creating a new version release
# This workflow is manually triggered to create a new version tag for the Babynames project
# This workflow only creates a tag and outputs it for debugging, but does not deploy anything

name: Bump version

# Trigger the workflow manually using the GitHub Actions UI
# This allows controlled releases when needed rather than on every push
on:
  workflow_dispatch

permissions:
  contents: 'write'

jobs:
  # Job to generate a new version tag based on semantic versioning
  # This creates a new git tag with an incremented version number
  tagging:
    runs-on: ubuntu-latest
    steps:
      # Use the cradle/actions/tag action to generate a semantic version tag
      # This automatically determines the next version number based on commit messages
      - name: Generate Tag
        id: tag_version
        uses: tschm/cradle/actions/tag@v0.1.72
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # The build job exports marimo notebooks to static HTML/WebAssembly
  build:
    needs: tagging
    runs-on: "ubuntu-latest"
    steps:
      - uses: jebel-quant/marimushka@v0.1.1
        with:
          notebooks_wasm: 'notebooks'
